language: node_js
node_js : 
    - "node"

before_script:
    - npm install -g gulp
    - npm install -g bower
    - bower install

script: gulp build

before_deploy:
    - rm .gitignore
    - echo -e "node_modules/\nbower_components/" > .gitignore

deploy:
  email: $GH_MAIL
  name: $GH_NAME
  provider: pages
  skip_cleanup: true
  github_token: $PAT
  on:
    branch: master

branches:
    only:
        - master
        - develop